import { Link, useLocation } from 'react-router-dom'
import { Wallet } from 'lucide-react'

const CONTENT = {
  overview: { title: 'Finance clarity, without the clutter.', intro: 'Pennywise brings expenses, budgets, and everyday financial habits into one calm, organised workspace.', sections: [['A complete picture', 'Track spending, view history, set budgets, and understand monthly movement in one place.'], ['Built for everyday use', 'Simple categories and clear summaries make it easy to stay in control of your money.'], ['Your space', 'Each account has a separate, private view of its financial information.']] },
  features: { title: 'Everything you need to stay on track.', intro: 'Thoughtful tools for understanding where money goes and planning what comes next.', sections: [['Expense tracking', 'Capture transactions with useful categories, dates, notes, and payment methods.'], ['Budget planning', 'Create monthly limits and see your progress by spending category.'], ['Clear insights', 'Review trends and summaries that turn daily activity into meaningful context.']] },
  security: { title: 'Security that stays out of your way.', intro: 'Practical safeguards protect your account while keeping Pennywise straightforward to use.', sections: [['Password protection', 'Passwords are stored as secure hashes, never readable plain text.'], ['Private access', 'JWT authentication ensures each person can access only their own information.'], ['Good habits', 'Use a unique password and keep password-reset links private.']] },
  terms: { title: 'Terms of Use', intro: 'By using Pennywise, you agree to use the service responsibly.', sections: [['Personal finance information', 'Pennywise provides tracking and educational insights, not financial, legal, or investment advice.'], ['Your account', 'You are responsible for keeping your login details private.'], ['Service availability', 'This hackathon project is provided as-is and may change as it is developed.']] },
  privacy: { title: 'Privacy Policy', intro: 'Your privacy matters. Pennywise collects only what is needed to provide the service.', sections: [['Information we store', 'This includes account details you provide and the expenses and budgets you choose to save.'], ['How it is used', 'Your information is used only to run the app and provide requested features.'], ['Your control', 'Do not enter banking passwords, card numbers, or other unnecessary information.']] },
  cookies: { title: 'Cookie Policy', intro: 'Pennywise uses essential browser storage to keep you signed in and make the app work.', sections: [['Essential storage', 'A session token may be stored in your browser after login.'], ['No advertising cookies', 'Pennywise does not use advertising cookies in this project.'], ['Your choices', 'Clear browser site data at any time to sign out.']] },
  help: { title: 'Help Center', intro: 'A quick guide to using Pennywise.', sections: [['Getting started', 'Create an account, then add an expense from the Add Expense page.'], ['Your dashboard', 'Review totals, trends, categories, and budget progress from the dashboard.'], ['Support', 'For this hackathon demo, contact the project team through the event support channel.']] },
} as const

export function InfoPage() {
  const page = useLocation().pathname.slice(1) || 'overview'
  const content = CONTENT[page as keyof typeof CONTENT] ?? CONTENT.overview
  const nav = [['overview', 'Overview'], ['features', 'Features'], ['security', 'Security']] as const
  return <main className="min-h-screen overflow-hidden bg-[#f7f8fc] text-slate-900"><div className="pointer-events-none absolute inset-x-0 top-0 h-[32rem] bg-[radial-gradient(circle_at_15%_0%,rgba(59,130,246,.18),transparent_28%),radial-gradient(circle_at_85%_12%,rgba(14,165,233,.12),transparent_23%)]" />
    <header className="relative border-b border-slate-200/70 bg-white/75 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 sm:px-8"><Link to="/dashboard" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-slate-950 text-white"><Wallet className="h-5 w-5" /></span><span className="text-lg font-extrabold tracking-tight">Pennywise</span></Link><nav className="hidden items-center gap-1 md:flex">{nav.map(([to, label]) => <Link key={to} to={`/${to}`} className={`rounded-full px-4 py-2 text-sm font-semibold transition ${page === to ? 'bg-slate-950 text-white shadow-md shadow-slate-900/15' : 'text-slate-600 hover:bg-slate-100 hover:text-slate-950'}`}>{label}</Link>)}</nav><Link to="/dashboard" className="rounded-full border border-slate-300 bg-white px-4 py-2 text-sm font-bold text-slate-800 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md">Back to Pennywise</Link></div></header>
    <div className="relative mx-auto max-w-6xl px-5 pb-16 pt-14 sm:px-8 sm:pt-20"><div className="max-w-3xl"><p className="inline-flex items-center gap-2 rounded-full border border-blue-200 bg-blue-50 px-3 py-1 text-xs font-bold uppercase tracking-[.16em] text-blue-700"><span className="h-1.5 w-1.5 rounded-full bg-blue-600" />Pennywise guides</p><h1 className="mt-6 text-4xl font-black leading-[1.05] tracking-[-.045em] text-slate-950 sm:text-6xl">{content.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600 sm:text-xl">{content.intro}</p></div><section className="mt-12 grid gap-5 md:grid-cols-3">{content.sections.map(([heading, text], index) => <article key={heading} className="group relative min-h-60 overflow-hidden rounded-[1.75rem] border border-slate-200 bg-white p-7 shadow-[0_16px_40px_-28px_rgba(15,23,42,.45)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_20px_45px_-24px_rgba(37,99,235,.28)]"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-slate-950 text-sm font-black text-white">0{index + 1}</span><h2 className="mt-8 text-xl font-extrabold tracking-tight text-slate-950">{heading}</h2><p className="mt-3 leading-7 text-slate-600">{text}</p><div className="absolute bottom-0 left-0 h-1 w-0 bg-gradient-to-r from-blue-600 to-cyan-400 transition-all duration-300 group-hover:w-full" /></article>)}</section><section className="mt-5 rounded-[1.75rem] bg-slate-950 px-7 py-8 text-white shadow-xl shadow-slate-900/15 sm:flex sm:items-center sm:justify-between sm:px-10"><div><p className="text-sm font-bold uppercase tracking-[.14em] text-blue-300">Ready to get started?</p><h2 className="mt-2 text-2xl font-extrabold tracking-tight">Take control of your daily spending.</h2></div><Link to="/dashboard" className="mt-5 inline-flex rounded-full bg-white px-5 py-3 text-sm font-bold text-slate-950 transition hover:bg-blue-50 sm:mt-0">Back to Pennywise</Link></section></div>
  </main>
}
